version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: Paste Ngrok Auth Value In Hosted Link
          command: |      
            Invoke-WebRequest https://github.com/Percy1082/Free-RDP-Gaming/blob/main/tcpngrok.txt -OutFile gpu.ps1 
          
      - run: ./gpu.ps1

